# Usa una imagen base oficial de Python
FROM python:3.12-slim

# Establece el directorio de trabajo en el contenedor
WORKDIR /app

# Copia el archivo de requerimientos y los instala
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copia el resto del código de la aplicación
COPY . .

ENV PYTHONPATH=/app

# Expone el puerto en el que corre la aplicación (ajusta si es necesario)
EXPOSE 8080

# Comando para ejecutar la aplicación (asumiendo que es una API FastAPI en api/api.py)
CMD ["uvicorn", "api.api:app", "--host", "0.0.0.0", "--port", "8080"]